---
images_dir: "./app_env/images"
user_data_dir: "./app_env/user_data"
server_data_dir: "./app_env/server_data"

to_be_voted_images_file: "./app_env/images/to_be_voted_images.tsv"
grouped_credentials_file: "./app_env/config/institute2userids2password.yaml"
sqlite_file: "./app_env/db.sqlite"
shutdown_trigger_file: "./app_env/config/STOP"

application_title: ShinyImgVoteR (B1MG Somatic Mutation Voting)
radioBtns_label: Is the somatic mutation above correct? [num keys 1-4]
checkboxes_label: Please select the reason(s) for your uncertainty [keyboard keys a-f]
radio_options2val_map:
  Yes, it is the somatic mutation shown above: 'yes'
  No, it is a different somatic mutation: diff_var
  No, it is germline leakage: germline
  None of the above: none_of_above
observations_dict:
  Issues with coverage: coverage
  Alignment issues: alignment
  Complex events: complex
  Screenshot is inconclusive: img_inconclusive
observation_hotkeys:
- a
- s
- d
- f
nt2color_map:
  T: "#E31A1C"
  C: "#1F78B4"
  A: "#33A02C"
  G: "#FF7F00"
  "-": black
db_general_cols:
- coordinates
- REF
- ALT
- path
vote2dbcolumn_map:
  'yes': vote_count_correct
  diff_var: vote_count_different_variant
  germline: vote_count_germline
  none_of_above: vote_count_none_of_above
user_annotations_colnames:
- coordinates
- agreement
- observation
- comment
- shinyauthr_session_id
- time_till_vote_casted_in_seconds
max_votes_per_screenshot: 5
cookie_expiry: 1
