training_answers_not_saved:
  - userid: test
    password: 1234
    admin: true

  - userid: test2
    password: abcd

institute1:
  - userid: test3
    password: NULL

  - userid: test4
    password: NULL
