---
images_dir: "./app_env/images"
user_data_dir: "./app_env/user_data"
server_data_dir: "./app_env/server_data"

to_be_voted_images_file: "./app_env/images/to_be_voted_images.tsv"
grouped_credentials_file: "./app_env/config/institute2userids2password.yaml"
sqlite_file: "./app_env/db.sqlite"
shutdown_trigger_file: "./app_env/config/STOP"

application_title: ShinyImgVoteR (B1MG Somatic Mutation Voting)
radioBtns_label: Is the somatic mutation above correct? [num keys 1-4]
checkboxes_label: Please select the reason for your uncertainty [keyboard keys a-g]
radio_options2val_map:
  Yes, it is a somatic mutation: 'yes'
  No, it is a different somatic mutation: diff_var  #should render a comment box
  No, it is a germline leakage: germline_leak
  The screenshot shows no or few reads supporting the mutation: no_or_few_reads
  None of the above, due to: not_confident
observations_dict:
  Issues with coverage: coverage
  Low allele frequency: low_vaf
  Alignment issues: alignment
  Complex event: complex
  Quality issues with the image: img_qual_issue
observation_hotkeys:
- a
- s
- d
- f
- g
nt2color_map:
  T: "#E31A1C"
  C: "#1F78B4"
  A: "#33A02C"
  G: "#FF7F00"
  "-": black
db_general_cols:
- coordinates
- REF
- ALT
- path
vote2dbcolumn_map:
  'yes': vote_count_correct
  'no': vote_count_no_variant
  diff_var: vote_count_different_variant
  not_confident: vote_count_not_sure
user_annotations_colnames:
- coordinates
- agreement
- observation
- comment
- shinyauthr_session_id
- time_till_vote_casted_in_seconds
cookie_expiry: 1
