---
user_data_dir: "./user_data"
server_data_dir: "./server_data"
images_dir: "./images"
sqlite_file: "./db.sqlite"
to_be_voted_images_file: "./screenshots/uro003_paths_mock.txt"
application_title: B1MG Somatic Mutation Voting
radioBtns_label: Is the somatic mutation above correct? [num keys 1-4]
checkboxes_label: Please select the reason for your uncertainty [keyboard keys a-h]
radio_options2val_map:
  Yes, it is: 'yes'
  There is no variant: 'no'
  There is a different variant: diff_var
  I'm not sure: not_confident
observations_dict:
  Issues with coverage: coverage
  Low allele frequency: low_vaf
  Alignment issues: alignment
  Complex event: complex
  Quality issues with the image: img_qual_issue
  Issue with the voting platform: platform_issue
observation_hotkeys:
- a
- s
- d
- f
- g
- h
nt2color_map:
  T: "#E31A1C"
  C: "#1F78B4"
  A: "#33A02C"
  G: "#FF7F00"
  "-": black
db_general_cols:
- coordinates
- REF
- ALT
- variant
- path
vote2dbcolumn_map:
  'yes': vote_count_correct
  'no': vote_count_no_variant
  diff_var: vote_count_different_variant
  not_confident: vote_count_not_sure
user_annotations_colnames:
- coordinates
- agreement
- alternative_vartype
- observation
- comment
- shinyauthr_session_id
- time_till_vote_casted_in_seconds
institute_ids:
- CNAG
- DKFZ
- DNGC
- FPGMX
- Hartwig
- ISCIII
- KU Leuven
- Latvian BRSC
- MOMA
- SciLifeLab
- Universidade de Aveiro
- University of Helsinki
- University of Oslo
- University of Verona
test_institute: Training_answers_not_saved
selected_institute_id: CNAG
selected_user_id: Test
cookie_expiry: 1
